package com.dingchao.schoolpay.shrio.entity;

import java.io.Serializable;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pla_sys_user.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pla_sys_user.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pla_sys_user.userpwd
     *
     * @mbggenerated
     */
    private String userpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pla_sys_user.orgid
     *
     * @mbggenerated
     */
    private Integer orgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pla_sys_user.abbr
     *
     * @mbggenerated
     */
    private String abbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pla_sys_user.parentid
     *
     * @mbggenerated
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pla_sys_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pla_sys_user.userid
     *
     * @return the value of pla_sys_user.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pla_sys_user.userid
     *
     * @param userid the value for pla_sys_user.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pla_sys_user.username
     *
     * @return the value of pla_sys_user.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pla_sys_user.username
     *
     * @param username the value for pla_sys_user.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pla_sys_user.userpwd
     *
     * @return the value of pla_sys_user.userpwd
     *
     * @mbggenerated
     */
    public String getUserpwd() {
        return userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pla_sys_user.userpwd
     *
     * @param userpwd the value for pla_sys_user.userpwd
     *
     * @mbggenerated
     */
    public void setUserpwd(String userpwd) {
        this.userpwd = userpwd == null ? null : userpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pla_sys_user.orgid
     *
     * @return the value of pla_sys_user.orgid
     *
     * @mbggenerated
     */
    public Integer getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pla_sys_user.orgid
     *
     * @param orgid the value for pla_sys_user.orgid
     *
     * @mbggenerated
     */
    public void setOrgid(Integer orgid) {
        this.orgid = orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pla_sys_user.abbr
     *
     * @return the value of pla_sys_user.abbr
     *
     * @mbggenerated
     */
    public String getAbbr() {
        return abbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pla_sys_user.abbr
     *
     * @param abbr the value for pla_sys_user.abbr
     *
     * @mbggenerated
     */
    public void setAbbr(String abbr) {
        this.abbr = abbr == null ? null : abbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pla_sys_user.parentid
     *
     * @return the value of pla_sys_user.parentid
     *
     * @mbggenerated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pla_sys_user.parentid
     *
     * @param parentid the value for pla_sys_user.parentid
     *
     * @mbggenerated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pla_sys_user
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userid=").append(userid);
        sb.append(", username=").append(username);
        sb.append(", userpwd=").append(userpwd);
        sb.append(", orgid=").append(orgid);
        sb.append(", abbr=").append(abbr);
        sb.append(", parentid=").append(parentid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}